-- AlterTable
ALTER TABLE `enquiries` ADD COLUMN `drop_note` VARCHAR(191) NULL,
    ADD COLUMN `drop_reason` ENUM('CLIENT_NOT_INTERESTED', 'PREMIUM_TOO_HIGH', 'WENT_WITH_COMPETITOR', 'CLIENT_UNREACHABLE', 'DUPLICATE_ENQUIRY', 'INVALID_DETAILS', 'OTHER') NULL,
    ADD COLUMN `dropped_at` DATETIME(3) NULL;
